# Generated by Django 3.2.21 on 2023-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(max_length=200)),
                ('_name', models.CharField(max_length=200)),
                ('_type', models.CharField(max_length=200)),
                ('_price', models.IntegerField(max_length=200)),
            ],
        ),
    ]
