# Generated by Django 3.2.21 on 2023-10-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parts',
            name='_price',
            field=models.IntegerField(),
        ),
    ]
