# Generated by Django 3.2.21 on 2023-10-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231017_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='_id',
            new_name='partId',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='_name',
            new_name='partName',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='_price',
            new_name='partPrice',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='_type',
            new_name='partType',
        ),
    ]
