# Generated by Django 3.2.21 on 2023-10-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20231017_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='partPrice',
            field=models.FloatField(),
        ),
    ]
