# Generated by Django 3.2.21 on 2023-10-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_parts_partprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='partClockUnit',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='partCoreClock',
            field=models.FloatField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='partNo',
            field=models.CharField(default=123123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='partReleaseDate',
            field=models.IntegerField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parts',
            name='partTDP',
            field=models.IntegerField(default=123214),
            preserve_default=False,
        ),
    ]
