# Generated by Django 3.2.21 on 2023-10-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20231017_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='partId',
            new_name='TDP',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partClockUnit',
            new_name='clock_unit',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partCoreClock',
            new_name='core_clock',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partNo',
            new_name='part_no',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partReleaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='partType',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='partTDP',
        ),
        migrations.AlterField(
            model_name='parts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
