# Generated by Django 3.2.21 on 2023-10-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231017_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
