# Generated by Django 3.2.21 on 2023-10-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_parts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='type',
        ),
    ]
