# Generated by Django 3.2.21 on 2023-10-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_parts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='type',
            field=models.CharField(default='CPU', max_length=200),
            preserve_default=False,
        ),
    ]
