# Generated by Django 3.2.21 on 2023-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_parts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='type',
            field=models.CharField(choices=[('CPU', 'GPU')], max_length=10),
        ),
    ]
