# Generated by Django 3.2.21 on 2023-10-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_parts_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='release_date',
            field=models.IntegerField(default=1234567789),
            preserve_default=False,
        ),
    ]
